export const T = {
  en: {
    topbar: '🚚 FREE shipping $150+ · 🔒 Secure Stripe · ↩️ 30-day returns · ⭐ 100% Positive Feedback · 🔵⚜️ Fièrement Québécois',
    searchPlaceholder: 'Search Hot Wheels, Star Wars, Marvel, LEGO...',
    search: 'Search', cart: 'Cart', shipping: '📦 Shipping', allItems: 'All', popular: '🔥 Deals',
    heroBadge: '🔥 New items added every week',
    heroTitle1: 'THE SHOP FOR', heroTitle2: 'TRUE COLLECTORS',
    heroSub: 'Liquidation & Discount · Hot Wheels · Star Wars · Marvel · DC · VHS · LEGO',
    heroCta: 'Browse deals →', heroPopular: '🔥 Hot deals',
    stat1n:'1 500+',stat1l:'Items in stock',stat2n:'9 000+',stat2l:'Real photos',
    stat3n:'100%',stat3l:'Positive feedback',stat4n:'🇨🇦',stat4l:'Canada & USA',
    categories:'Browse by Category', newArrivals:'🆕 New Arrivals',
    seeAll:'See all →', mostPopular:'🔥 Most Popular',
    new:'NEW', openBox:'OPEN BOX', addCart:'+ Cart', added:'✓ Added',
    sold:'sold', myCart:'MY CART', emptyCart:'Your cart is empty',
    estimatedTotal:'Estimated total', checkout:'PROCEED TO CHECKOUT →',
    secureStripe:'🔒 Secure payment by Stripe',
    trust1t:'Secure Payment',trust1d:'Stripe SSL 256-bit',
    trust2t:'Careful Packaging',trust2d:'Every item protected',
    trust3t:'Ships from Canada',trust3d:'To Canada & USA',trust_qc:'🔵⚜️ Fièrement Québécois',
    trust4t:'100% Feedback+',trust4d:'Thousands of eBay sales',
    trust5t:'30-Day Returns',trust5d:'Satisfaction guaranteed',
    trust6t:'Discount Prices',trust6d:'Liquidation & deals',
    aboutBadge:'Our Story', aboutTitle:'WHO ARE WE?',
    aboutP1:'Born2BeToys is a Quebec-based shop passionate about vintage toys, collectibles and great deals. We are collectors first.',
    aboutP2:'Our mission: the best Hot Wheels, Star Wars, Marvel, DC, Transformers, Hallmark and more at discount and liquidation prices.',
    aboutP3:'Based in Quebec, Canada. We ship across Canada and the USA. Every item carefully packaged.',
    aboutWhat:'WHAT WE SELL', aboutCta:'Browse the shop →',
    shippingPage:'SHIPPING & RETURNS',
    freeShipping:'🎉 FREE shipping on orders $150+!',
    freeShippingDesc:'On all orders of $150+ delivered in Canada.',
  },
  fr: {
    topbar: '🚚 Livraison GRATUITE dès 150$ · 🔒 Paiement Sécurisé · ↩️ Retours 30 jours · ⭐ 100% Feedback · 🔵⚜️ Fièrement Québécois',
    searchPlaceholder: 'Hot Wheels, Star Wars, Marvel, LEGO...',
    search: 'Chercher', cart: 'Panier', shipping: '📦 Livraison', allItems: 'Tout', popular: '🔥 Liquidation',
    heroBadge: '🔥 Nouveaux articles chaque semaine',
    heroTitle1: 'LA BOUTIQUE DES', heroTitle2: 'VRAIS COLLECTIONNEURS',
    heroSub: 'Liquidation & Discount · Hot Wheels · Star Wars · Marvel · DC · VHS · LEGO',
    heroCta: 'Voir les aubaines →', heroPopular: '🔥 Liquidation',
    stat1n:'1 500+',stat1l:'Articles en stock',stat2n:'9 000+',stat2l:'Photos réelles',
    stat3n:'100%',stat3l:'Feedback positif',stat4n:'🇨🇦',stat4l:'Canada & USA',
    categories:'Parcourir par catégorie', newArrivals:'🆕 Nouveaux Arrivages',
    seeAll:'Voir tout →', mostPopular:'🔥 Les Plus Populaires',
    new:'NEUF', openBox:'OPEN BOX', addCart:'+ Panier', added:'✓ Ajouté',
    sold:'vendus', myCart:'MON PANIER', emptyCart:'Votre panier est vide',
    estimatedTotal:'Total estimé', checkout:'PASSER À LA CAISSE →',
    secureStripe:'🔒 Paiement sécurisé par Stripe',
    trust1t:'Paiement Sécurisé',trust1d:'Stripe SSL 256-bit',
    trust2t:'Emballage Soigné',trust2d:'Chaque article protégé',
    trust3t:'Expédié du Canada',trust3d:'Vers Canada & USA',trust_qc:'🔵⚜️ Fièrement Québécois',
    trust4t:'100% Feedback+',trust4d:'Des milliers de ventes eBay',
    trust5t:'Retours 30 jours',trust5d:'Satisfaction garantie',
    trust6t:'Prix Discount',trust6d:'Liquidation & aubaines',
    aboutBadge:'Notre Histoire', aboutTitle:'QUI SOMMES-NOUS ?',
    aboutP1:"Born2BeToys est une boutique québécoise passionnée par les jouets vintage et les collectibles. On est des collectionneurs avant tout.",
    aboutP2:"Notre mission : les meilleurs Hot Wheels, Star Wars, Marvel, DC, Transformers, Hallmark et plus — à des prix discount et de liquidation.",
    aboutP3:"Basés au Québec, Canada. On expédie partout au Canada et aux États-Unis. Chaque article emballé avec soin.",
    aboutWhat:"CE QU'ON VEND", aboutCta:'Explorer la boutique →',
    shippingPage:'LIVRAISON & RETOURS',
    freeShipping:'🎉 Livraison GRATUITE dès CA$150 !',
    freeShippingDesc:'Sur toutes les commandes de 150$+ livrées au Canada.',
  }
}
